services:
  fbl-rag-api:
    build: .
    container_name: fbl-rag-api
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uv run fastapi dev --host 0.0.0.0 --port 8001
