[project]
name = "fidelitybank-rag-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "chromadb>=1.4.1",
    "fastapi[all]>=0.128.4",
    "ollama>=0.6.1",
    "scalar-fastapi>=1.6.1",
    "sqlmodel>=0.0.32",
]
